### ISSUE TITLE
The `Cargo.toml` repository Url should probably be updated?

### ISSUE THREAD

**Issue by Skgland** [rust-lang/gccjit.rs#40]
It looks like <https://github.com/antoyo/gccjit.rs> redirects to this repository.

- [ ] https://github.com/rust-lang/gccjit.rs/blob/master/Cargo.toml#L8
- [ ] https://github.com/rust-lang/gccjit.rs/blob/master/gccjit_sys/Cargo.toml#L9

**Comment by antoyo** [comment]
Yes, this should be updated. Thanks for noticing this!
