### ISSUE TITLE
gccjit 2.1.0 and gccjit_sys 0.2.0 crates.io release not in git

### ISSUE THREAD

**Issue by Skgland** [rust-lang/gccjit.rs#41]
The crates.io repository link redirects here (#40), but the code here looks to be still 2.0.0 and 0.1.0 respectively (based on the version in `Cargo.toml`). The code for the releases 19 days ago appears absent.

**Comment by antoyo** [comment]
Seems like I forgot to push. Sorry about that.

**Comment by Skgland** [comment]
While that matches the commit sha `9ae0279ff9a83baa0d18b6eef69861ef3881ba84` from [gccjit](https://docs.rs/crate/gccjit/latest/source/.cargo_vcs_info.json), it looks like the commit sha `ca40e787acf5124c72219957d915ba6122f2a9ac` from [gccjit_sys](https://docs.rs/crate/gccjit_sys/latest/source/.cargo_vcs_info.json) is different and still missing here.

**Comment by antoyo** [comment]
I do have this commit locally. I'm not sure what happened, but the branch containing this commit seems to be missing the update of the dependency version, so I guess I did something in a branch, did a deploy and forgot to update this version and maybe fixed it in another branch.
Is this an issue that the commit is not found?

**Comment by Skgland** [comment]
Ah, found it [Blog Post](https://lawngno.me/blog/2024/06/10/divine-provenance.html) [Top 999 Crates Results](https://lawngnome.github.io/divine-provenance/)

**Comment by antoyo** [comment]
Could you please describe what you would want in this case?

**Comment by Skgland** [comment]
Technically the commit could be pushed to a different branch and tagged so that its available, but given that the packaged content of gccjit_sys 0.2.0 on crates.io is (after undoing the expected changes from packaging) identical to the gccjit_sys folder in this repo at `9ae0279ff9a83baa0d18b6eef69861ef3881ba84 ` I don't think that is necesary, so this is just something to maybe keep in mind for future publishes.
